#!/bin/bash
# This script installs AuditD on Linux and then configures for searching SSH users

# Update package list and install auditd
echo "Updating package list and installing auditd..."
apt-get update -y && apt-get install -y auditd

# Configure audit rules
echo "Configuring audit rules..."
cat <<EOT > /etc/audit/rules.d/audit.rules
# SSH auth events, such as USER_AUTH and USER_LOGIN, are generated by the PAM system during SSH logins.
-a always,exit -F arch=b64 -S execve -C uid!=euid -F key=tty-audit
-a always,exit -F arch=b64 -S execve -C uid!=euid -F key=ssh-logins
-w /etc/ssh/sshd_config -p wa -k ssh-config
-w /var/log/auth.log -p wa -k auth-log
EOT

# Configure PAM for SSHD
echo "Configuring PAM for SSHD..."
if ! grep -q "pam_tty_audit.so enable=" /etc/pam.d/sshd; then
    echo "session required pam_tty_audit.so enable=* disable=root" >> /etc/pam.d/sshd
fi

# Configure PAM for local logins
echo "Configuring PAM for local logins..."
if ! grep -q "pam_tty_audit.so enable=" /etc/pam.d/login; then
    echo "session required pam_tty_audit.so enable=*" >> /etc/pam.d/login
fi

# Restart services
echo "Restarting SSHD and AuditD services..."
systemctl restart sshd
systemctl restart auditd

echo "AuditD installation and configuration completed successfully!"


# Output section: Run ausearch commands and display results based on username provided

# Prompt the user for a username
echo "Please enter the username you want to search for in the audit logs:"
read username

# Validate that the username is not empty
if [ -z "$username" ]; then
    echo "Error: No username entered. Exiting."
    exit 1
fi

# Check if the username exists on the system
if ! id "$username" &>/dev/null; then
    echo "Error: The username '$username' does not exist on this system. Exiting."
    exit 1
fi

echo "Running auditctl and ausearch commands to display audit logs for user: $username"

# Display current audit rules
echo "Current audit rules:"
sudo auditctl -l

# Search for login events related to the entered username and display the last 5 entries
echo "Last 4 login events related to '$username':"
ausearch -i | grep -i "$username" | grep -i login | tail -n 5

# Search for TTY-related events for the entered username and highlight 'data'
echo "TTY-related events for '$username' with 'data' highlighted:"
ausearch -i | grep -i "$username" | grep --color=always TTY | grep -i data

# Display all audit logs from today until now
echo "Audit logs from today until now:"
ausearch -i --start today --end now

echo "AuditD installation, configuration, and log inspection completed successfully!"